### ISSUE TITLE
Adding @melund

### ISSUE THREAD

**Issue by scopatz** [conda-forge/xonsh-feedstock#1]
Hello @pelson and @pelson, how do I add @melund to the xonsh team?

**Comment by scopatz** [comment]
ie this might be a request for permissions :)

**Comment by pelson** [comment]
The xonsh team comes from the recipe:
https://github.com/conda-forge/xonsh-feedstock/blob/master/recipe/meta.yaml#L41

Looks like you are already in:

![screen shot 2016-02-10 at 16 53 47](https://cloud.githubusercontent.com/assets/810663/12954546/f2bff782-d016-11e5-8804-3c50138bc6ae.png)

Just submit a PR, and next time the CI runs on ```conda-forge/conda-forge.github.io``` that person will be added to the team (and anyone not on the list anymore will be removed)

**Comment by scopatz** [comment]
Ahhh That is awesome. Magical even.

**Comment by pelson** [comment]
> Ahhh That is awesome. Magical even.

No magic here. https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/update_teams.py :stuck_out_tongue_winking_eye:

**Comment by melund** [comment]
Cool. Thanks a lot.
